### ISSUE TITLE
Your solution to problem 2.9(b)

### ISSUE THREAD

**Issue by xulongwu4** [ArthurZC23/Machine-Learning-A-Probabilistic-Perspective-Solutions#1] opened 2017-06-15 19:58 UTC
The proposition in problem 2.9(b) is actually false. You can find a counter example here:
https://github.com/astahlman/MLaPP/blob/master/solutions/ch2.pdf

**Comment by ArthurZC23** [comment] 2017-06-15 21:04
Greetings @xulongwu4. Thank you for the feedback. 
The counter example on the link is not valid. The problem is that the second assumption (X indep Y | W) is not valid for the variables he has created. Yes, X, Y and Z are independent by construction. However, W is a function of X, Y and Z. Therefore, its statement that "Given W, knowledge  of Y gives no additional information about X" is false, because Y gives information about W = XYZ, which in turn gives information about X.
In the extreme case, if what the author said was true, then given W, knowledge  of Y and Z would give no additional information about X and we would have P(X |W, Y, Z) = P(X|W). However, if we know W, Y and Z, we know how to calculate X [X = W/(YZ)] and P(X =  W/(YZ)) = 1.
Another good example of X, Y independent and P(X, Y | f(X,Y)) not being independent can be found at: [math.stack](https://math.stackexchange.com/questions/1900375/is-it-possible-that-two-independent-variables-become-dependent-conditioning-on-a).
As for the validity of the true statement, just think about information gain. If W supplies enough information for X to be irrelevant to Y , then adding more information (in this case Z) will not make this untrue!

**Comment by xulongwu4** [comment] 2017-06-15 21:39
Hello ArthurZC23,

The second condition, (X indep Y | W) is still valid in this example in my opinion because no information of Z is given. We know W is a function of X, Y and Z. If we only know W, which means we know XYZ, knowledge of Y still gives no information on X since Z is involved here and it is independent of X and Y.

In that example, we can easily calculate the following:
P(X=1|W=1) = 1/2, P(X=-1|W=1) = 1/2, P(X=1|W=-1) = 1/2, P(X=-1|W=-1)=1/2
P(Y=1|W=1) = 1/2, P(Y=-1|W=1) = 1/2, P(Y=1|W=-1) = 1/2, P(Y=-1|W=-1)=1/2

We also have the following:
P(X=1,Y=1|W=1) = 1/4
P(X=1,Y=-1|W=1) = 1/4
P(X=-1,Y=1|W=1) = 1/4
P(X=-1,Y=-1|W=1) = 1/4

It is similar for W=-1.

So we can see that P(X,Y|W)=P(X|W)*P(Y|W).

The point here is that X and Y are independent if we are given information only on Z. It is different than the situation of P(X,Y|f(X,Y)). It is actually P(X,Y|f(X,Y,Z)).

**Comment by ArthurZC23** [comment] 2017-06-16 11:20
@xulongwu4 I have to say that I am starting to agree with you. Let's take for example W = XYZ = 1. This reduces the sample space on (X, Y, Z) to the following possibilities {(1, 1, 1), (-1, -1, 1), (-1, 1, -1), (1, -1, -1)}, each having the same probability. Therefore, we can do a marginalization and arrive at P(X = 1 | W = 1) = P(X = 1, Y = 1, Z =1 | W =1) + P(X = 1, Y = -1, Z =-1 | W =1) + P(X = 1, Y = 1, Z =-1 | W =1) + P(X = 1, Y = -1, Z =1 | W =1) = 1/4 + 1/4 + 0 + 0 = 1/2 (like you said). Using marginalization, we can also arrive at P(X = 1, Y = 1 | W = 1) = P(X = 1, Y = 1, Z =1 | W =1) + P(X = 1, Y = 1, Z =-1 | W =1) = 1/4 + 0 = 1/4 (like you said). Thus, P(X = 1, Y = 1 | W = 1) = P(X = 1| W = 1) P(Y = 1| W = 1) = 1/4. Since we can make this to all combinations of values, the assumption is indeed true!
As for the final result: P(X, Y | W, Z) = P(X | W, Z)P(X | W, Z, Y). Since X, Y and Z are i.i.d. then P(X | W, Z) = P(X | W) = 1/2, by the same reasoning we did above. Furthermore, P(X | W, Z, Y) = 1 or 0. So, P(X, Y | W, Z) = 1/2I(XYZ = W) != P(X | W, Z)P(Y | W, Z) = 1/4!
Thanks again for your feedback. Not only I learned a lot with you, but also you helped all the readers of this repository :smile:! I will update this question in next couple of days to warn readers about the changes. If you don't mind I will also do a special thanks to you.
Cheers.

**Comment by xulongwu4** [comment] 2017-06-16 12:56
Many thanks to you @ArthurZC23  for making this amazing repository!

If you will do a special thanks, I think it is also worth mentioning the original repository which proposed this counter example.

**Comment by ArthurZC23** [comment] 2017-06-17 14:23
No problem, already on it. As soon as I update the solution, I will close this issue ok?

**Comment by ArthurZC23** [comment] 2017-06-17 15:34
New solution is already online in the repository.

**Closed as completed by ArthurZC23** 2017-06-17 15:34 UTC
